"""Documentation generation with embedded images and git commit hashes."""
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional, Union


def _get_git_hash() -> Optional[str]:
    """Get current git commit hash, or None if not in a git repo."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return None


def generate_documentation(
    title: str,
    algorithm_desc: str,
    commit_hash: Optional[str] = None,
    images: Optional[List[Union[str, Path]]] = None,
    output_path: Optional[Union[str, Path]] = None,
) -> str:
    """Generate a markdown documentation file.

    Args:
        title: Document title.
        algorithm_desc: Description of the algorithm or change.
        commit_hash: Git commit hash. Auto-detected if None.
        images: List of image/GIF paths to embed.
        output_path: If provided, write markdown to this file.

    Returns:
        The generated markdown string.
    """
    if commit_hash is None:
        commit_hash = _get_git_hash() or "unknown"

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# {title}",
        "",
        f"**Date**: {timestamp}",
        f"**Commit**: `{commit_hash}`",
        "",
        "## Description",
        "",
        algorithm_desc,
        "",
    ]

    if images:
        lines.append("## Visuals")
        lines.append("")
        for img in images:
            img_path = Path(img)
            lines.append(f"![{img_path.stem}]({img_path})")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by GenesisTools on {timestamp}*")

    content = "\n".join(lines)

    if output_path is not None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")

    return content
